---
title: "Homework 1"
date: 5/23/24
editor: visual
draft: false
---

## Problem 1

Using the following code:

```{r}
x <- matrix(rnorm(1500), nrow = 10)
```

Write the code to produce the output if you use the `rowMeans()` on the R object `x`.

```{r}
#| code-fold: true
#| code-summary: Answer

xmeans <- vector(length = nrow(x))
for(i in 1:nrow(x)){
  xmeans[i] <- mean(x[i,])
}
#xmeans
```

## Problem 2

Using the following code:

```{r}
y <- matrix(sample(1:400, 100, replace = T), nrow = 10)
```

Find the median value for each column of the matrix `y`. You are not allowed to use the `median()` function.

```{r}
#| code-fold: true
#| code-summary: Answer

ymedian <- vector(length = ncol(x))
for(i in 1:nrow(x)){
  ymedian[i] <- sum(x[5:6,]) / 2
}
#ymedian
```

## Problem 3

Write the code that will generate the first 1000 numbers of the [Fibonacci Sequence](https://en.wikipedia.org/wiki/Fibonacci_sequence).

```{r}
#| code-fold: true
#| code-summary: Answer

fib <- c(0,1)
for(i in 3:1000){
  fib <- c(fib, fib[i-2] + fib[i-1])
}
#fib
```
